version: '3'

services:
    web:
        image: ayrtoncasa/sitesecurepass:latest
        container_name: ContainerSite
        env_file:
            - .env
        restart: always
        ports:
            - "80:80"
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: ayrtoncasa/bdsecurepass:latest
        container_name: ContainerBanco
        environment:
            MYSQL_ROOT_PASSWORD: urubu100
        restart: always
        volumes:
        - db_data:/var/lib/mysql
        - ./BancoDadosSP:/docker-entrypoint-initdb.d/
        ports:
            - "3306:3306"
        networks:
            - app-network
        

networks:
    app-network:
        driver: bridge

volumes:
    db_data: